### ISSUE TITLE
it slowly moves downward

### ISSUE THREAD

**Issue by jquatier** [gregwhitaker/jqflag#1]
When I put the flag into JQ mode, I have to unplug it from power or else it slowly moves back into GSD mode. Is this a bug?

**Comment by gregwhitaker** [comment]
That sounds like a bug.  Is the servo making noise?  Perhaps it is not zeroed anymore?  If you look at the code you will see that when we put it together I had to set the stop at 93 when it should be 90 in order to keep the thing from slowly turning when in the stop position.  Maybe the old servo is starting to give out.  I would try tweaking that stop value.

**Comment by gregwhitaker** [comment]
@jquatier can we close this?
